replicaCount: 2

image:
  repository: discovery-cpp
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: [ ]

serviceAccount:
  create: true
  automount: true
  annotations: { }
  name: ""

podAnnotations: { }
podLabels: { }

podSecurityContext: { }

securityContext: { }

nodeSelector: { }

tolerations: [ ]

affinity: { }
